ARG REGISTRY_URL=
FROM ${​​​​​​​REGISTRY_URL}​​​​​​​tensorflow/tensorflow:2.7.1-gpu-jupyter

RUN apt-get update -yq \
 && apt-get install -yq --no-install-recommends \
    wget \
    vim \
    python3-pip

RUN mkdir -p /opt/code/aiduez \
    && mkdir -p /opt/conda/bin

RUN ln -s /usr/local/bin/jupyter /opt/conda/bin/jupyter

WORKDIR /opt/code/aiduez
COPY . /opt/code/aiduez

RUN pip install --upgrade pip \
 && pip install -r requirements.txt

RUN jupyter notebook --generate-config

COPY custom/aiduez_config.yml /root/.aiduez/aiduez_config.yml
COPY custom/custom.css /root/.jupyter/custom/custom.css
COPY custom/index.html.j2 /usr/local/share/jupyter/nbconvert/templates/lab/index.html.j2
COPY custom/configuration.py /usr/local/lib/python3.8/dist-packages/voila/configuration.py
COPY app.ipynb /aihub/workspace/app.ipynb 

WORKDIR /aihub/workspace